baseurl = "https://www.connectionwith.us/"
languageCode = "en-us"
title = "Bringing Together Arlo and Heather"
theme = "arcanum"
disqusShortname = "connectionwith-us"
googleAnalytics = "UA-122715474-1"
preserveTaxonomyNames = true
paginate = 30
pluralizeListTitles = false
enableRobotsTXT = true
canonifyURLs = true
relativeURLs = true
enableEmoji = true
enableGitInfo = true
footnoteAnchorPrefix = "fn-"
footnoteReturnLinkContents = "back to text"
noChmod = true

[taxonomies]
	tag = "tags"

[related]
	threshold = 70
	includeNewer = true
	toLower = true

[[related.indices]]
	name = "keywords"
	weight = 150
[[related.indices]]
	name  = "author"
	weight = 30
[[related.indices]]
	name  = "tags"
	weight = 100
[[related.indices]]
	name  = "date"
	weight = 10
	pattern = "2006"

[params]
	shareMenuInNav = false
  # Sets the meta tag description
  description          = "Arlo and Heather should be committed! So we are doing that. Connect with our journey before, during, and after the event. We love you!"
  navbarTitle          = "Arlo & Heather"
	date_format = "2 January 2006"
  # Sets where "View More Posts" links
  viewMorePostLink     = "/conversation"

# Optional Params
  # Sets navbarTitle to match the section of the website
  dynamicTitles        = true
  # Sets RSS icons to appear on the sidebar with the social media buttons
  rssAppearAtTop       = false
  rssAppearAtBottom    = true
  # Sets Social Media icons to appear on the sidebar
  socialAppearAtTop    = true
  socialAppearAtBottom = true
  # Sets Categories to sort by number of posts instead of alphabetical
  categoriesByCount    = true
  # Sets Estimated Reading Time to appear in post headers
  includeReadingTime   = true
  # Sets the Favicon and Version for the site. Default support is for
  # apple-touch-icon-precomposed.png, favicon.png, favicon.ico, and mstile.png.
  # These are stored in the favicon folder. See the following for more information:
  # https://github.com/audreyr/favicon-cheat-sheet
  loadFavicon          = false
  faviconVersion       = ""
  # Sets Social Share links to appear on posts
  socialShare          = true
  # Sets specific share to appear on posts (default behavior is to appear)
  socialShareTwitter   = true
  socialShareGoogleplus = false
  socialShareFacebook  = true
  socialShareReddit    = false
  socialShareLinkedin  = false
  socialShareStumbleupon = false
  socialSharePinterest = false
  socialShareEmail     = true

  # Load custom CSS or JavaScript files. The variable is an array so that you
  # can load multiple files if necessary. You can also load the standard theme
  # files by adding the value, "default".
  customCSS            = ["default", "css/add-on.css"]
  customJS             = ["default"]

[params.homepage]
  shared_css = "index/common.css"

# Extend with the sections that you want on the home page. Each is loaded from a partial.
[[params.homepage.sections]]
partial = "index/hero.html"
css = "index/hero.css"

[[params.homepage.sections]]
partial = "index/conversation.html"

[[params.homepage.sections]]
partial = "index/news.html"
css = "index/news-row.css"

[[params.homepage.sections]]
partial = "index/pick-your-poison.html"
css = "index/pick-your-poison.css"

[[params.homepage.sections]]
partial = "index/photos.html"
css = "index/photos-row.css"

[[params.homepage.sections]]
partial = "index/key-logistics.html"
css = ""

[[params.homepage.sections]]
partial = "index/site-todo.html"
css = ""

[[params.homepage.sections]]
partial = "index/react-scripts.html"

# Sets the menu items in the navigation bar
# Identifier prepends a Font Awesome icon to the menu item
[[menu.main]]
  name = "Home"
  url = "/"
  identifier = "fab fa-fort-awesome"
  weight = 2

[[menu.main]]
  name = "Photos"
  url = "/photos"
  identifier = "fas fa-camera-retro"
  weight = 3

[[menu.main]]
  name = "Wedding Weekend Events"
  url = "/events"
  identifier = "fas fa-cocktail"
  weight = 4

[[menu.main]]
  name = "Conversation"
  url = "/conversation"
  identifier = "far fa-comments"
  weight = 5

# Sets Social Media icons to appear and link to your account. Value should be your
# username unless otherwise noted. These are the icons affected by socialAppearAtTop
# and socialAppearAtBottom.
[social]
  flickr           = ""
  slideshare       = ""
  facebook         = "arlo.belshee"
  youtube          = ""
  vimeo            = ""
  instagram        = ""
  telegram         = ""
	twitter = "arlobelshee"

# To get the index.css. Don't modify.
[outputs]
	home = ["HTML", "RSS", "CSS"]

[mediaTypes]
[mediaTypes."text/css"]
suffixes = ["css"]

[outputFormats]
[outputFormats.css]
name = "CSS"
mediaType = "text/css"
path = "css"
baseName = "index"
isPlainText = true
isHTML = false
notAlternative = true
