title = "Arlo Belshee"
baseURL = "https://arlobelshee.com"
languageCode = "en-us"
theme = "airspace-hugo"

[menu]

  [[menu.header]]
    weight = 6
    name = "About"
    url = "/about"
  [[menu.header]]
    weight = 5
    name = "Past Work"
    url = "/work"
  [[menu.header]]
    weight = 4
    name = "Technical Articles"
    url = "/techies"
  [[menu.header]]
    weight = 3
    name = "Services"
    url = "/service"
  [[menu.header]]
    weight = 2
    name = "Contact"
    url = "/contact"

  [[menu.footer]]
    weight = 1
    name = "About us"
    url = "#"
  [[menu.footer]]
    weight = 2
    name = "Contact us"
    url = "#"
  [[menu.footer]]
    weight = 3
    name = "How it works"
    url = "#"
  [[menu.footer]]
    weight = 4
    name = "Blog"
    url = "#"
  [[menu.footer]]
    weight = 5
    name = "Terms"
    url = "#"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  date_format = "6 January 2006"

  home = "Home"

  [params.slider]
    enable = true
    title = "Mending the World's Legacy Code"
    subtitle = "We love legacy code.<br/>We help you love yours."

  [params.wrapper]
    enable = true
    title = "About Us"
    italic = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics"
    paragraph = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id"

  [params.blog]
    enable = true
    longtitle = "Long Articles for Techies"
    subtitle = "Sometimes in-depth, sometimes simply meandering, these articles don't gloss over important details."

  [params.feature]
    enable = true
    title = "We believe in great ideas"
    content = "Maecenas faucibus mollis interdum.\n\nMorbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus."
    [params.feature.button]
      caption = "Nifty stuff"
      url = "#"

  [params.call]
    enable = true
    title = "Sign up to stop having bugs."
    paragraph = "Understand what causes bugs to be written, and then learn to code in a way that simply writes fewer of them."

  [params.testimonial]
    enable = true
    title = "People love us."
    paragraph = "Look at all these people!"

  [params.contact]
    enable = true
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Stop by for a visit"
      address = "North Main Street, Brooklyn Australia"
      email = "Email: contact@mail.com"
      phone = "Phone: +88 01672 506 744"
    [params.contact.gmaps]
      title = "Directions"
    [[contact.social]]
      weight = 1
      url = "https://twitter.com/arlobelshee"
      icon = "fa-twitter"
    [[contact.social]]
      weight = 2
      url = "https://github.com/arlobelshee"
      icon = "fa-github"
