# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Arcanum"
license = "MIT"
licenselink = "LICENSE.md"
description = "An alchemical blend of concepts to create a magical theme for a company."
homepage = "https://arlobelshee.com/"
tags = ["blog", "responsive", "font awesome", "highlight.js", "fancybox 3"]
features = ["html5", "css3", "responsive"]
min_version = 0.41

[author]
  name = "Arlo Belshee"
  homepage = "https://arlobelshee.com"
